# Streamlit Cloud에서 사용할 환경변수 설정
# 실제 배포 시에는 Streamlit Cloud의 Secrets Management에서 설정하세요

[DATABASE_URL]
# Supabase 연결 문자열 (실제 값으로 교체 필요)
# 형식: postgresql+psycopg2://postgres:비밀번호@db.fjaxvaegmtbsyogavuzy.supabase.co:5432/postgres?sslmode=require
DATABASE_URL = "postgresql+psycopg2://postgres:YOUR_PASSWORD@db.fjaxvaegmtbsyogavuzy.supabase.co:5432/postgres?sslmode=require"
