# Streamlit Cloud에서 사용할 환경변수 설정
# 실제 배포 시에는 Streamlit Cloud의 Secrets Management에서 설정하세요

# 로컬 테스트용 (실제 비밀번호로 교체하세요)
DATABASE_URL = "postgresql+psycopg2://postgres:Nwk5JYywxV3ATT8M@db.fjaxvaegmtbsyogavuzy.supabase.co:5432/postgres?sslmode=require"
